// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeacherManagement.data;

#nullable disable

namespace TeacherManagementEF.Migrations
{
    [DbContext(typeof(TeacherDbContext))]
    partial class TeacherDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TeacherManagement.data.Teacher", b =>
                {
                    b.Property<int>("Teacher_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Teacher_Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Teacher_Location")
                        .HasColumnType("longtext");

                    b.Property<string>("Teacher_Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Teacher_Qualification")
                        .HasColumnType("longtext");

                    b.HasKey("Teacher_Id");

                    b.ToTable("Teachers");
                });
#pragma warning restore 612, 618
        }
    }
}
